application: qldt2neu
version: chinh
runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:

- url: /assets
  static_dir: assets

- url: /favicon.ico
  static_files: assets/img/favicon.ico
  upload: assets/img/favicon.ico

- url: /.*
  script: main.application

- url: /assets/fonts/(.*\.ttf)
  mime_type: font/truetype
  static_files: assets/fonts/\1
  upload: assets/fonts/(.*\.ttf)
# [END handlers]
error_handlers:
- file: overquota.html 
- error_code: over_quota
  file: overquota.html


# [START libraries]
libraries:
- name: webapp2
  version: latest
# [END libraries]
